 
var moviedata=[
  {
    id: 1,
    nameChinese:'绿皮书',
    nameEnglish:'Green Book',
    prop:'剧情 喜剧 传记',
    country:'美国/130分钟',
    score: '豆瓣：8.9',
    language:'我住在城堡里，孤身一人',
    home: require('./image/week1/home.jpg'),
    detail:require('./image/week1/detail.jpg'),
    introducej:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂',
    introduce:'在充满异域风情的古代阿拉伯王国，善良的穷小子阿拉丁（莫纳·马苏德 饰）和勇敢的茉莉公主 （纳奥米·斯科特 饰）浪漫邂逅，在可以满足主人公三个愿望的神灯精灵 （威尔·史密斯 饰）的帮助下，两人踏上了一次寻找真爱和自我的魔幻冒险',
    actor:[ {arl:require('./image/week1/1.jpg'),name:'彼得·法雷里', name2:'导演'},
            {arl:require('./image/week1/2.jpg'),name:'维果·莫腾森', name2:'饰 托尼·利'},
            {arl:require('./image/week1/3.jpg'),name:'马赫沙拉·阿里', name2:'饰 唐·雪利'},
            {arl:require('./image/week1/4.jpg'),name:'琳达·卡德里尼', name2:'饰 德洛瑞丝'},
            {arl:require('./image/week1/5.jpg'),name:'塞巴斯·马尼斯科', name2:'饰 约翰尼'},
            {arl:require('./image/week1/6.jpg'),name:'迪米特·马里诺夫', name2:'饰 奥列格'},
            {arl:require('./image/week1/7.jpg'),name:'迈克·哈顿', name2:'饰 乔治'},
          ],
     vedio:[
            {arl:require('./image/week1/11.jpg') },
            {arl:require('./image/week1/12.jpg') },
            {arl:require('./image/week1/13.jpg') },
            {arl:require('./image/week1/14.jpg') },
            {arl:require('./image/week1/15.jpg') },
            {arl:require('./image/week1/16.jpg') },
            {arl:require('./image/week1/17.jpg') },
            {arl:require('./image/week1/18.jpg') },
         ],
      expand:'https://movie.douban.com/subject/27060077/',
      lan:[
         
        {intro:'The world is full of lonely people waiting to make the first move.',
        intro2:' 世界上孤独的人都害怕迈出第一步。',
        intro3:'--绿皮书   '}, 
        {intro:'You never win with violence. You only win when you maintain your dignity.',
        intro2:'你永远不会以暴力取胜。只有保持尊严才能战胜一切。',
        intro3:'--绿皮书   '}, 
        {intro:'I am not white enough, not black enough and even not man enough.',
        intro2:' 我不够白，也不够黑，甚至不够男人。',
        intro3:'--绿皮书   '}, 
        {intro:'.My father used to say,whatever you do, do it a hundred percent.when you eat, eat like it is your last meal.',
        intro2:' 不管你做什么 都要做到极致，上班就认真工作笑就尽情大笑，吃东西时 就像是最后一餐那样去享受。',
        intro3:'--绿皮书   '}, 
        {intro:'They did not have a choice whether to be inside or out. You did.',
        intro2:' 他们没有选择是否进场的权力，但你有。',
        intro3:'--绿皮书   '}, 
        {intro:'Because genius is not enough. It takes courage to change people is hearts.',
        intro2:' 因为光靠天赋是不够的 改变大众的想法需要勇气。',
        intro3:'--绿皮书   '}, 
        {intro:'My time and experiences without you are meaningless to me.',
        intro2:' 没有你的时光和旅程对我来说毫无意义。',
        intro3:'--绿皮书   '}, 
        {intro:' Falling in love with you was the easiest thing I have ever done.',
        intro2:' 与你相爱是我所做过的最轻松的事。',
        intro3:'--绿皮书   '}, 
      ]
  },
  {
    id: 2,
    nameChinese:'海蒂和爷爷',
    nameEnglish:'Heidi ',
    prop:'剧情 家庭 冒险',
    country:'德国/111分钟',
    score: '豆瓣：9.1',
    language:'如果生活中有什么使你感到快乐，那就去做吧，不要管别人说了什么。',
    home:require('./image/week2/home.jpg'),
    detail:require('./image/week2/detail.jpg'),
    introduce:'海蒂 很小就失去了父母，无依无靠伶仃飘零，所幸得到了姨妈的收留，然而，这照顾却不能够持久，最终，海蒂来到了阿尔卑斯山，投奔住在那里的爷爷。在村民们眼中，爷爷是个倔强而又古怪的老头，对 其敬而远之，然而海蒂那双天真无邪的眼睛发现了爷爷深藏在内心的柔情，一老一少两人卸下心防，相依为命。 一个名为皮特的放羊男孩成为了海蒂的新朋友，两人之间结下了深厚的友谊。可是好景不长，海蒂被迫离开了爷爷和皮特，来到了富家小姐克劳拉家中，做她的玩伴。克劳拉的双腿因幼年生病不能行走，个性亦因此而内向怪癖，海蒂的到来替她打开了新世界的大门，找回了久违的快乐。',
    actor:[ {arl:require('./image/week2/1.jpg'),name:'阿兰·葛斯彭纳', name2:'导演'},
            {arl:require('./image/week2/2.jpg'),name:'阿努克·斯特芬', name2:'饰 海蒂'},
            {arl:require('./image/week2/3.jpg'),name:'布鲁诺·甘茨', name2:'饰 爷爷'},
            {arl:require('./image/week2/4.jpg'),name:'昆林·艾格匹', name2:'饰 彼得 '},
            {arl:require('./image/week2/5.jpg'),name:'安娜·申茨', name2:'饰 姨妈'},
            {arl:require('./image/week2/6.jpg'),name:'伊莎贝尔·奥特曼', name2:'饰 克拉拉'},
            {arl:require('./image/week2/7.jpg'),name:'莉莲·奈福', name2:'饰 巴贝儿'},
          ],
     vedio:[
            {arl:require('./image/week2/11.jpg') },
            {arl:require('./image/week2/12.jpg') },
            {arl:require('./image/week2/13.jpg') },
            {arl:require('./image/week2/14.jpg') },
            {arl:require('./image/week2/15.jpg') },
            {arl:require('./image/week2/16.jpg') },
            {arl:require('./image/week2/17.jpg') },
            {arl:require('./image/week2/18.jpg') },
            {arl:require('./image/week2/19.jpg') },
            {arl:require('./image/week2/20.jpg') },
            {arl:require('./image/week2/21.jpg') }, 
 ],
 expand:'https://movie.douban.com/subject/25958717/',
 lan:[
         
  {intro:'Good morning, Grandfather.  - Drink your milk.',
  intro2:' 早上好，爷爷  - 喝你的牛奶',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'People like saying nasty things. You have to decide whether to trust your own eyes and ears.',
  intro2:'人们喜欢讨论邪恶的东西，你需要自己判断，相信自己的眼睛和耳朵。',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'Pfarrer: It is your Christian duty to look affer your grandchild. ',
  intro2:'牧师：照看你的孙女，是你对上帝的义务。',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'If you could read you would know how the story continues.And you like stories, don not you?',
  intro2:' 如果你现在会读书的话，就可以知道故事接下来发生了什么。你喜欢故事，不是吗？ ',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'You just say that because you still can it read.',
  intro2:' 你这样说是因为你不会读书 ',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'I would rather stay with Grandfather.',
  intro2:'我还是想和爷爷待在一起',
  intro3:'--海蒂和爷爷  '}, 
  {intro:'We could have such a nice time together.',
  intro2:' 我们能够一起度过一段美好时光。',
  intro3:'--海蒂和爷爷  '}, 
  {intro:' Did you see that?  - Yes, a shooting star.',
  intro2:'  看到了吗  - 星星在闪耀',
  intro3:'--海蒂和爷爷  '}, 
]
  },
  {
    id: 3,
    nameChinese:'奇迹男孩',
    nameEnglish:'Wonder',
    prop:'剧情 家庭 儿童',
    country:'美国/113分钟',
    score: "豆瓣: 8.6",
    language:'你就是一个奇迹男孩',
    home:require('./image/week3/home.jpg'),
    detail:require('./image/week3/detail.jpg'),
    introduce:'   奥吉是一个10岁的男孩，除了头戴一个巨大的太空头盔外，他和其他的同年龄孩子别无二致。头盔下隐藏了奥吉因为各种手术而伤痕累累的脸庞，它不仅完美的隐藏起了奥吉脆弱自卑的内心，也成功的防止了奥吉的模样吓到别的孩子。奥吉没有上过学，他的所有文化知识都是母亲伊莎贝尔在家教授给他的。然而，伊莎贝尔渐渐感觉到，家庭课堂无法满足奥吉的成长需要，除了学习知识，奥吉还必须学会的，是如何同除了家人以外的人交流。在忧虑重重之中，伊莎贝尔将奥吉送入了一间公立学校里，在那里，奥吉面临的是他人生中必须要战胜的挑战。',
    actor:[ {arl:require('./image/week3/1.jpg'),name:'斯蒂芬·卓博斯基', name2:'导演'},
            {arl:require('./image/week3/2.jpg'),name:'雅各布·特伦布莱', name2:'饰 奥吉'},
            {arl:require('./image/week3/3.jpg'),name:'朱莉娅·罗伯茨', name2:'饰 伊莎贝尔'},
            {arl:require('./image/week3/4.jpg'),name:'伊扎贝拉·维多维', name2:'饰 维娅'},
            {arl:require('./image/week3/5.jpg'),name:'欧文·威尔逊', name2:'饰 内特'},
            {arl:require('./image/week3/6.jpg'),name:'诺亚·尤佩', name2:'饰 杰克·威尔'},
            {arl:require('./image/week3/7.jpg'),name:'丹妮尔·罗丝', name2:'饰 米兰达'},
          ],
     vedio:[
            {arl:require('./image/week3/11.jpg') },
            {arl:require('./image/week3/12.jpg') },
            {arl:require('./image/week3/13.jpg') },
            {arl:require('./image/week3/14.jpg') },
            {arl:require('./image/week3/15.jpg') },
            {arl:require('./image/week3/16.jpg') },
            {arl:require('./image/week3/17.jpg') },
            {arl:require('./image/week3/18.jpg') },
            {arl:require('./image/week3/19.jpg') },
            {arl:require('./image/week3/20.jpg') },
            {arl:require('./image/week3/21.jpg') },
            {arl:require('./image/week3/22.jpg') },
    ],
    expand:'https://movie.douban.com/subject/26787574/',
    lan:[
         
      {intro:'My mom always said "If you don not like where you are just picture where you wanna be By Auggie.',
      intro2:' 我妈妈常说，“如果你不喜欢这里，就想象一个你想去的地方。”',
      intro3:'--奇迹男孩 '}, 
      {intro:'"When given the choice between being right or being kind, choose kind". Mr Brown is September Precet',
      intro2:'如果要从正确和善良中，作出选择，请选择善良。',
      intro3:'--奇迹男孩 '}, 
      {intro:'While nothing justifies striking another student…I know good friends are worth defending.',
      intro2:' 虽然殴打同学的行为不能通融，但我知道友情是值得捍卫的。',
      intro3:'--奇迹男孩 '}, 
      {intro:'Because school sucks. And people change. So if you wanna be a normal kid, Auggie, then those are the rules.',
      intro2:' 上学就是这么糟糕。人也是会变的。如果你想当普通小孩奥吉，这就是规则。',
      intro3:'--奇迹男孩 '}, 
      {intro:'Maybe if we knew what other people were thinking, we wouldd know that no one is ordinary.',
      intro2:' 如果我们了解别人的想法，就会知道，没有人是普通的。 ',
      intro3:'--奇迹男孩 '}, 
      {intro:' And we all deserve a standing ovation at least once in our lives.',
      intro2:'每个人都值得大家站起来为他鼓掌一次。',
      intro3:'--奇迹男孩 '}, 
      {intro:'Because I am your mom, it counts the most because I know you the most.',
      intro2:' 正因为我是你妈妈，所以我的看法才重要，因为我才是最了解你的人。',
      intro3:'--奇迹男孩 '}, 
      {intro:' Kindness is everywhere, all you need to do is look.',
      intro2:' 善良无处不在，你所需要做的就是看看。',
      intro3:'--奇迹男孩 '}, 
    ]
  },
  {
    id: 4,
    nameChinese:'天才少女 ',
    nameEnglish:'Gifted',
    prop:'剧情 家庭',
    country:'美国/101分钟',
    score: '豆瓣：8.2',
    language:' 我聆听风的声音越过我灵魂的风声',
    home:require('./image/week4/home.jpg'),
    detail:require('./image/week4/detail.jpg'),
    introduce:'Chris Evans将参演马克·韦布（超凡蜘蛛侠系列）执导新片《Gifted》。该片讲述美队扮演一名原本波士顿大学助教现在是修船工的Frank Adler在姐姐自杀后领养了外甥女Mary——一位智力过人的天才少女。Mary刚一入学就表现得与众不同，然而舅舅Frank只想让孩子过普通人生活。Mary的外婆得知了少女的天赋，出现在二人的生活里，要将Mary培养成数学天才。于是一场抚养权之争开始了。',
    actor:[ {arl:require('./image/week4/1.jpg'),name:'马克·韦布', name2:'导演'},
            {arl:require('./image/week4/2.jpg'),name:'克里斯·埃文斯', name2:'饰 弗兰克·阿德勒'},
            {arl:require('./image/week4/3.jpg'),name:'珍妮·斯蕾特', name2:'饰 邦妮·史蒂文森'},
            {arl:require('./image/week4/4.jpg'),name:'琳赛·邓肯', name2:'饰 伊芙琳·阿德勒'},
            {arl:require('./image/week4/5.jpg'),name:'麦肯娜·格瑞丝', name2:'饰 玛丽·阿德勒'},
            {arl:require('./image/week4/6.jpg'),name:'奥克塔维亚', name2:'饰 罗伯塔·泰勒 '},
            {arl:require('./image/week4/7.jpg'),name:'维迈克尔·肯德尔', name2:'饰 贾斯汀·吉尔莫尔 '},
          ],
     vedio:[
            {arl:require('./image/week4/11.jpg') },
            {arl:require('./image/week4/12.jpg') },
            {arl:require('./image/week4/13.jpg') },
            {arl:require('./image/week4/14.jpg') },
            {arl:require('./image/week4/15.jpg') },
            {arl:require('./image/week4/16.jpg') },
            {arl:require('./image/week4/17.jpg') },
            {arl:require('./image/week4/18.jpg') },
            {arl:require('./image/week4/19.jpg') },
            {arl:require('./image/week4/20.jpg') },
 ],
  expand:'https://movie.douban.com/subject/26593587/',
  lan:[
         
    {intro:'Youknow, there is something you could be overlooking.',
    intro2:' 有些事是可以不在乎的。”',
    intro3:'--天才少女 '}, 
    {intro:'I listen to the wind To the wind of mysoul.',
    intro2:'我聆听风的声音越过我灵魂的风声。',
    intro3:'--天才少女 '}, 
    {intro:'where I will end up Well, I think.',
    intro2:'我将会在哪里停下我的脚步 我想。',
    intro3:'--天才少女 '}, 
    {intro:' There arsan are ple and tree analogy lurking.',
    intro2:' 俗话说有其母必有其子。',
    intro3:'--天才少女 '}, 
    {intro:'nobody likes a smart-ass.',
    intro2:' 没人喜欢自作聪明的人。',
    intro3:'--天才少女 '}, 
    {intro:' Frank says I am not supposed to correctolder people. ',
    intro2:'弗兰克说我不要去指出长辈的错误。',
    intro3:'--天才少女 '}, 
    {intro:'That you will be waking up in all thesebetter days .',
    intro2:'此刻你正在越来越美好的日子里慢慢醒来。 ',
    intro3:'--天才少女 '}, 
    {intro:' These simple things mean more than Ican say.',
    intro2:' 这些简单的事远不只我描述的样子。',
    intro3:'--天才少女 '}, 
  ]
  },
  {
    id: 5,
    nameChinese:'摔跤吧！爸爸',
    nameEnglish:'Dangal',
    prop:'剧情 家庭 传记 运动',
    country:'印度/140分钟',
    score: '豆瓣：9.0',
    language:'不要给你的对手任何机会，你的对手也不会给你任何机会。',
    home:require('./image/week5/home.jpg'),
    detail:require('./image/week5/detail.jpg'),
    introduce:' 　马哈维亚（阿米尔·汗 Aamir Khan 饰）曾经是一名前途无量的摔跤运动员，在放弃了职业生涯后，他最大的遗憾就是没有能够替国家赢得金牌。马哈维亚将这份希望寄托在了尚未出生的儿子身上，哪知道妻子接连给他生了两个女儿，取名吉塔 和巴比塔 。让马哈维亚没有想到的是，两个姑娘展现出了杰出的摔跤天赋，让他幡然醒悟，就算是女孩，也能够昂首挺胸的站在比赛场上，为了国家和她们自己赢得荣誉。就这样，在马哈维亚的指导下，吉塔和巴比塔开始了艰苦的训练，两人进步神速，很快就因为在比赛中连连获胜而成为了当地的名人。为了获得更多的机会，吉塔进入了国家体育学院学习，在那里，她将面对更大的诱惑和更多的选择。',
    actor:[ {arl:require('./image/week5/1.jpg'),name:'涅提·蒂瓦里', name2:'导演'},
            {arl:require('./image/week5/2.jpg'),name:'阿米尔·汗', name2:'饰 马哈维亚·辛格'},
            {arl:require('./image/week5/3.jpg'),name:'法缇玛·萨那', name2:'饰 吉塔·珀尕'},
            {arl:require('./image/week5/4.jpg'),name:'桑亚·玛荷塔', name2:'饰 芭比塔·库马尔·'},
            {arl:require('./image/week5/5.jpg'),name:'阿帕尔夏克提', name2:'饰 奥姆卡尔'},
            {arl:require('./image/week5/6.jpg'),name:'沙克希·坦沃', name2:'饰 达雅·考尔'},
            {arl:require('./image/week5/7.jpg'),name:'塞伊拉·沃西', name2:'饰 小吉塔'},
          ],
     vedio:[
            {arl:require('./image/week5/11.jpg') },
            {arl:require('./image/week5/12.jpg') },
            {arl:require('./image/week5/13.jpg') },
            {arl:require('./image/week5/14.jpg') },
            {arl:require('./image/week5/15.jpg') },
            {arl:require('./image/week5/16.jpg') },
            {arl:require('./image/week5/17.jpg') },
            {arl:require('./image/week5/18.jpg') },
            {arl:require('./image/week5/19.jpg') },
            {arl:require('./image/week5/20.jpg') },
      ],
    expand:'https://movie.douban.com/subject/26387939/',
    lan:[
         
      {intro:'Medalist don not grow on trees. you have to nurture them with love, with hard work, with dedication.',
      intro2:' 金牌选手不会从天而降，你必须用热爱、刻苦和投入来浇灌他们。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'Always respect your motherland  because the amount of respect you give to your motherland  you will get that much respect from your motherland.',
      intro2:'永远尊敬你的祖国，你会因为对祖国的尊敬而获得祖国对你同等的尊敬 。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'I am here to stay, just to be the strongest.',
      intro2:' 　　我在此停留，只为成为最强者。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'one second when your opponent makes a mistake.',
      intro2:' 只要你抓住了对手犯错的那一秒钟（你就赢了）。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'Even a rhinoceros applies strength  but a tiger applies strength and technique, both we should become a tiger and not a rhinoceros.',
      intro2:' 犀牛虽然很有力量，但老虎能同时运用力量和技巧。我们应该成为老虎而不是犀牛。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'By building your body you don not become a wrestler ... wrestling is something that is in the blood.',
      intro2:' 光打造身体，你是成不了一个摔跤选手的。摔跤是一种融入血液的东西。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:'No one supports you to get a medal ... but when you don not win a medal then everyone curses you.',
      intro2:' 没有人支持你去拿奖牌，但如果你不赢块奖牌回来，所有人都会诅咒你。',
      intro3:'--摔跤吧，爸爸 '}, 
      {intro:' Before you fight you need to fight with your fear.',
      intro2:' 战斗之前，你需要战胜自己的恐惧。',
      intro3:'--摔跤吧，爸爸 '}, 
    ]
  },
  {
    id: 6,
    nameChinese:'我不是药神',
    nameEnglish:'Save',
    prop:'剧情 喜剧',
    country:'中国/117分钟',
    score: '豆瓣：9.0',
    language:' ',
    home:require('./image/week6/home.jpg'),
    detail:require('./image/week6/detail.jpg'), 
    introduce:'普通中年男子程勇（徐峥 饰）经营着一家保健品店，失意又失婚。不速之客吕受益的到来，让他开辟了一条去印度买药做“代购”的新事业，虽然困难重重，但他在这条“买药之路”上发现了商机，一发不可收拾地做起了治疗慢粒白血病的印度仿制药独家代理商。程勇昔日的小舅子曹警官奉命调查仿制药的源头，假药贩子张长林 和瑞士正牌医药代表也对其虎视眈眈，生意逐渐变成了一场关于救赎的拉锯战。',
    actor:[ {arl:require('./image/week6/1.jpg'),name:'文牧野', name2:'导演'},
            {arl:require('./image/week6/2.jpg'),name:'陈峥', name2:'饰 程勇'},
            {arl:require('./image/week6/3.jpg'),name:'王传君', name2:'饰 吕受益'},
            {arl:require('./image/week6/4.jpg'),name:'周一围', name2:'饰 曹斌'},
            {arl:require('./image/week6/5.jpg'),name:'谭卓', name2:'饰 刘思慧'},
            {arl:require('./image/week6/6.jpg'),name:'章宇', name2:'饰 黄毛'},
            {arl:require('./image/week6/7.jpg'),name:'杨新鸣', name2:'饰 刘牧师'},
          ],
     vedio:[
            {arl:require('./image/week6/11.jpg') },
            {arl:require('./image/week6/12.jpg') },
            {arl:require('./image/week6/13.jpg') },
            {arl:require('./image/week6/14.jpg') },
            {arl:require('./image/week6/15.jpg') },
            {arl:require('./image/week6/16.jpg') },
            {arl:require('./image/week6/17.jpg') },
            {arl:require('./image/week6/18.jpg') },
            {arl:require('./image/week6/19.jpg') },
            {arl:require('./image/week6/20.jpg') },
            {arl:require('./image/week6/21.jpg') },
     ],
     expand:'https://movie.douban.com/subject/26752088/',
     lan:[
         
      {intro:'There is only one disease in the world, that is,poverty.',
      intro2:' 世界上只有一种病，就是穷病。',
      intro3:'--我不是药神  '}, 
      {intro:'He is only 20 years old. He is just trying to live, and what his crime.',
      intro2:'他才20岁，他只是想活着，犯了什么罪。',
      intro3:'--我不是药神  '}, 
      {intro:'They can not afford genuine medicine, and they are waiting for me to bring them back to save their lives.',
      intro2:' 他们根本吃不起正版药，他们就等着我把药带回去救他们的命。',
      intro3:'--我不是药神  '}, 
      {intro:'It is only my hope that this society will become better in the future.',
      intro2:' 我只希望，未来这个社会可以变的更好一点。',
      intro3:'--我不是药神  '}, 
      {intro:'I don not want to die. I want to live.',
      intro2:' 我不想死，我想活着。',
      intro3:'--我不是药神  '}, 
      {intro:'I admit that I broke the law. No matter how the verdict is, I have no objection.',
      intro2:'我承认，我犯法了，无论怎么判决，我没有异议。 ',
      intro3:'--我不是药神  '}, 
      {intro:'Money is the life.',
      intro2:'命就是钱。',
      intro3:'--我不是药神  '}, 
      {intro:'I don not want to be a savior. I just want to make money.',
      intro2:' 我不想做什么救世主，我只想赚钱。',
      intro3:'--我不是药神  '}, 
    ]
  },
  {
    id: 7,
    nameChinese:'头号玩家',
    nameEnglish:'Ready Player One',
    prop:'动作 科幻 冒险',
    country:'美国/140分钟',
    score: '豆瓣：8.7',
    language:'谢谢你玩我的游戏',
    home:require('./image/week7/home.jpg'),
    detail:require('./image/week7/detail.jpg'), 
    introduce:'故事发生在2045年，虚拟现实技术已经渗透到了人类生活的每一个角落。詹姆斯哈利迪（马克·里朗斯 Mark Rylance 饰）一手建造了名为“绿洲”的虚拟现实游戏世界，临终前，他宣布自己在游戏中设置了一个彩蛋，找到这枚彩蛋的人即可成为绿洲的继承人。要找到这枚彩蛋，必须先获得三把钥匙，而寻找钥匙的线索就隐藏在詹姆斯的过往之。',
    actor:[ 
            {arl:require('./image/week7/1.jpg'),name:'史蒂文·斯皮尔伯格 ', name2:'导演'},
            {arl:require('./image/week7/2.jpg'),name:'泰伊·谢里丹', name2:'饰 韦德·沃兹'},
            {arl:require('./image/week7/3.jpg'),name:'奥利维亚·库克', name2:'饰 萨曼莎'},
            {arl:require('./image/week7/4.jpg'),name:'本·门德尔森 ', name2:'饰 诺兰·索伦托'},
            {arl:require('./image/week7/5.jpg'),name:'马克·里朗斯', name2:'饰 詹姆斯·哈利迪'},
            {arl:require('./image/week7/6.jpg'),name:'丽娜·维特', name2:'饰 艾奇'},
            {arl:require('./image/week7/7.jpg'),name:'森崎温', name2:'饰 大东'},
          ],
    vedio: [
            {arl:require('./image/week7/11.jpg') },
            {arl:require('./image/week7/12.jpg') },
            {arl:require('./image/week7/13.jpg') },
            {arl:require('./image/week7/14.jpg') },
            {arl:require('./image/week7/15.jpg') },
            {arl:require('./image/week7/16.jpg') },
            {arl:require('./image/week7/17.jpg') },
            {arl:require('./image/week7/18.jpg') },
     ],
    expand:'https://movie.douban.com/subject/4920389/',
    lan:[
         
      {intro:'This is the "oasis" world, where the only limit is your own imagination.',
      intro2:' 这是“绿洲”世界，在这里唯一限制你的是你自己的想象力 ',
      intro3:'--头号玩家 '}, 
      {intro:'I am telling you this now because the future is in crisis.',
      intro2:'你我现在跟你们说这些，是因为未来陷入了危机。',
      intro3:'--头号玩家 '}, 
      {intro:'There are many people who ha.ve lost their lives. It is a war to control the future.',
      intro2:'现在有很多人都失去了生命，这是一场控制未来的战争。',
      intro3:'--头号玩家 '}, 
      {intro:'If reality ever scares me and makes me miserable, it is only in reality that I can truly eat a good meal.',
      intro2:' 即使现实再令我恐惧，再令我痛苦，也只有在现实中，我才能真正吃顿好饭。',
      intro3:'--头号玩家 '}, 
      {intro:'Whether you like it or not, the ones that go forward dont go backwards.',
      intro2:' 不管你喜不喜欢 该往前的不会后退。',
      intro3:'--头号玩家 '}, 
      {intro:'Ask yourself, are you willing to fight for it?',
      intro2:' 问问你自己，你愿意为此而战吗?',
      intro3:'--头号玩家 '}, 
      {intro:'Its not just a game. Im talking about life and death in the real world.',
      intro2:'这不仅仅是一个游戏，我说的是现实世界中的生死。',
      intro3:'--头号玩家 '}, 
      {intro:' Find him. Welcome to the rebellion.',
      intro2:' 找到他，欢迎加入起义军。',
      intro3:'--头号玩家 '}, 
    ]
  },
]

export default moviedata;